GestionDesWookies/Controllers/DroideController.cs
using StarWarsLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDesWookies.Controllers
{
    public class DroideController : Controller
    {
        private DroideDataLayer _dataLayer = new DroideDataLayer();

        // GET: Droide
        public ActionResult Index()
        {
            return View(this._dataLayer.SelectAll());
        }

        [HttpGet]
        public ActionResult Create()
        {
            this.SetModeleList();

            return this.View();
        }

        [HttpPost]
        public ActionResult Create(Droide droide)
        {
            this._dataLayer.Add(droide);

            this.SetModeleList();
            return this.View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            this.SetModeleList();

            Droide droide = this._dataLayer.SelectOne(id);

            return this.View(droide);
        }

        [HttpPost]
        public ActionResult Edit(Droide droide)
        {
            this._dataLayer.Edit(droide);

            this.SetModeleList();
            return this.View(droide);
        }

        private void SetModeleList()
        {
            this.ViewBag.ListeModele = (new ModeleDataLayer()).SelectAll();
        }
    }
}

GestionDesWookies/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDesWookies.Controllers
{
    public class GameController : Controller
    {
        public ActionResult Start(int nbWookies, int nbDroides, string nomPlanete)
        {
            return this.View();
        }
    }
}

GestionDesWookies/Controllers/HomeController.cs
using StarWarsLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDesWookies.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<Wookie> list = (new WookieDataLayer()).SelectAll();

            this.ViewBag.MesWookies = list;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GestionDesWookies/Controllers/PlaneteController.cs
using StarWarsLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDesWookies.Controllers
{
    public class PlaneteController : Controller
    {
        // GET: Plaenete
        public ActionResult Index()
        {
            return View();
        }

        // GET: Plaenete/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Plaenete/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Plaenete/Create
        [HttpPost]
        public ActionResult Create(Planete planete)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Plaenete/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Plaenete/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Plaenete/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Plaenete/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionDesWookies/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDesWookies.Controllers
{
    public class PlayerController : Controller
    {
        // GET: Player
        public ActionResult Login(string email)
        {
            return View();
        }
    }
}

GestionDesWookies/Controllers/WookieController.cs
using StarWarsLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionDesWookies.Controllers
{
    public class WookieController : Controller
    {
        // GET: Wookie
        public ActionResult Index()
        {
            List<Wookie> list = (new WookieDataLayer()).SelectAll();

            return View(list);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public ActionResult Create(Planete wookie)
        {
            return this.View();
        }
    }
}

GestionDesWookies/Views/Droide/Create.cshtml
@model StarWarsLibrary.Droide

@{
    ViewBag.Title = "Create";

    List<StarWarsLibrary.Modele> listModele = this.ViewBag.ListeModele;

}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Droide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Matricule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDeFabrication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ModeleId,
                                      listModele.Select(item => new SelectListItem() { Text = item.Libelle,
                                                                                       Value = item.Id.ToString()}))

                @*@Html.EditorFor(model => model.DateDeFabrication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDeFabrication, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionDesWookies/Views/Droide/Edit.cshtml
@model StarWarsLibrary.Droide

@{
    ViewBag.Title = "Create";

    List<StarWarsLibrary.Modele> listModele = this.ViewBag.ListeModele;
    List<SelectListItem> items = listModele.Select(item => new SelectListItem()
    {
        Text = item.Libelle,
        Value = item.ID.ToString(),
        Selected = item.ID == Model.Modele.ID
    }).ToList();
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(item => item.ID)

    <div class="form-horizontal">
        <h4>Droide</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Matricule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModeleID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ModeleID,
                                      items)

                @*@Html.EditorFor(model => model.DateDeFabrication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDeFabrication, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionDesWookies/Views/Droide/Index.cshtml
@model IEnumerable<StarWarsLibrary.Droide>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDeFabrication)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Matricule)
        </td>
        <td>
        </td>
        <td>
            @{ 
                string monUrl = Url.Action("Edit", "Droide", new { id = item.Id });
            }

            <a href="@monUrl">MonUrl</a>

            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

GestionDesWookies/Views/Game/Start.cshtml
@{
    ViewBag.Title = "Start";
}

<h2>Start</h2>

GestionDesWookies/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


@foreach (var item in this.ViewBag.MesWookies)
{
    <div>
        @item.Nom
    </div>
}

GestionDesWookies/Views/Planete/Create.cshtml
@model StarWarsLibrary.Planete

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Planete</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionDesWookies/Views/Player/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

GestionDesWookies/Views/Wookie/Create.cshtml
@model StarWarsLibrary.Wookie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Wookie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Sexe)
                    @Html.ValidationMessageFor(model => model.Sexe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDeNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDeNaissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDeNaissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionDesWookies/Views/Wookie/Index.cshtml
@model IEnumerable<StarWarsLibrary.Wookie>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDeNaissance)
        </th>
        <th>
            Planète
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateDeNaissance)
        </td>
        <td>
            @item.MaPlanete.Nom
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>